# Generated by Django 2.1.10 on 2019-07-23 18:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(default=' ', upload_to='media/stock')),
                ('homepage', models.CharField(default='', max_length=300)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('imageQ', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/stock')),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('free', models.BooleanField(default=False)),
                ('cost', models.CharField(blank=True, default='', max_length=100)),
                ('homepage', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField()),
                ('imageQ', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/stock')),
                ('slug', models.SlugField(default=' ', max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodasf.City')),
                ('county', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.County')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('imageQ', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/stock')),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('contact', models.CharField(default='', max_length=200)),
                ('bio', models.TextField(default='bio goes here')),
                ('picture', models.ImageField(default=' ', upload_to='media/faces')),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Local_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=300)),
                ('headline', models.CharField(default='', max_length=150)),
                ('posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('imageQ', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/stock')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.City')),
                ('county', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.County')),
                ('issue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Issue')),
                ('journalist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Journalist')),
            ],
            options={
                'ordering': ('-posted',),
            },
        ),
        migrations.CreateModel(
            name='Media_Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('home_page', models.CharField(default='', max_length=200)),
                ('date_founded', models.DateField(default='1956-02-27')),
                ('logo', models.ImageField(upload_to='media/logos')),
                ('description', models.TextField()),
                ('slug', models.SlugField(default=' ', max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodasf.City')),
                ('county', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.County')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(default=' ', upload_to='media/stock')),
                ('homepage', models.CharField(default='', max_length=300)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(default=' ', upload_to='media/faces')),
                ('homepage', models.CharField(default='', max_length=300)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default=' ', max_length=100)),
                ('county', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.County')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodasf.Level')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodasf.Party')),
                ('upcoming', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodasf.Event')),
            ],
        ),
        migrations.CreateModel(
            name='STF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='media/stock')),
                ('credit', models.CharField(default='', max_length=200)),
                ('update', models.TextField()),
                ('date_updated', models.DateTimeField()),
                ('videoQ', models.BooleanField(default=False)),
                ('video', models.CharField(blank=True, default='', max_length=500)),
                ('slug', models.SlugField(default=' ', max_length=200)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.City')),
                ('county', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.County')),
            ],
        ),
        migrations.CreateModel(
            name='STF_Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('banner', models.ImageField(upload_to='media/stock')),
                ('credit', models.CharField(default='', max_length=200)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(default=' ', max_length=200)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.City')),
                ('county', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.County')),
            ],
            options={
                'ordering': ('-date_updated',),
            },
        ),
        migrations.CreateModel(
            name='STF_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodasf.Media_Org')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodasf.STF')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('imageQ', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/stock')),
                ('slug', models.SlugField(default=' ', max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodasf.City')),
                ('county', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.County')),
            ],
        ),
        migrations.AddField(
            model_name='stf',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodasf.STF_Hub'),
        ),
        migrations.AddField(
            model_name='local_link',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodasf.Media_Org'),
        ),
        migrations.AddField(
            model_name='journalist',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodasf.Media_Org'),
        ),
        migrations.AddField(
            model_name='event',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodasf.Genre'),
        ),
        migrations.AddField(
            model_name='city',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodasf.County'),
        ),
    ]
