# Generated by Django 2.1.10 on 2019-07-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(default=' ', upload_to='media/stock')),
                ('homepage', models.CharField(default='', max_length=300)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default=' ', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='slug',
            field=models.SlugField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='county',
            name='slug',
            field=models.SlugField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.SlugField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='level',
            name='slug',
            field=models.SlugField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='party',
            name='slug',
            field=models.SlugField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(default=' ', max_length=100),
        ),
    ]
