# Generated by Django 2.1.10 on 2019-07-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0002_auto_20190724_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongressDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default=' ')),
                ('slug', models.SlugField(default=' ', max_length=100)),
                ('cities', models.ManyToManyField(to='nodasf.City')),
                ('county', models.ManyToManyField(to='nodasf.County')),
            ],
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='politician',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.CongressDistrict'),
        ),
    ]
