# Generated by Django 2.1.10 on 2019-07-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0003_auto_20190724_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='homepage',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
