# Generated by Django 2.1.10 on 2019-07-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0003_auto_20190722_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='id',
        ),
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.RemoveField(
            model_name='county',
            name='id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='id',
        ),
        migrations.RemoveField(
            model_name='journalist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='level',
            name='id',
        ),
        migrations.RemoveField(
            model_name='media_org',
            name='id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='id',
        ),
        migrations.RemoveField(
            model_name='party',
            name='id',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='id',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='id',
        ),
        migrations.AlterField(
            model_name='agency',
            name='slug',
            field=models.SlugField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='county',
            name='slug',
            field=models.SlugField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='slug',
            field=models.SlugField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='slug',
            field=models.SlugField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='slug',
            field=models.SlugField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='media_org',
            name='slug',
            field=models.SlugField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='party',
            name='slug',
            field=models.SlugField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='politician',
            name='slug',
            field=models.SlugField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
    ]
