# Generated by Django 2.1.10 on 2019-07-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0005_auto_20190724_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='media/stock'),
        ),
    ]
