# Generated by Django 2.1.10 on 2019-07-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0006_county_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressdistrict',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='media/stock'),
        ),
    ]
