# Generated by Django 2.1.10 on 2019-07-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0007_congressdistrict_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CongressDistrict',
            new_name='District',
        ),
    ]
