# Generated by Django 2.1.10 on 2019-07-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0008_auto_20190725_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Level'),
        ),
    ]
