# Generated by Django 2.1.10 on 2019-07-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0009_district_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('name',)},
        ),
    ]
