# Generated by Django 2.1.10 on 2019-07-25 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0010_auto_20190725_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Venue'),
        ),
        migrations.AddField(
            model_name='venue',
            name='homepage',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
