# Generated by Django 2.1.10 on 2019-07-26 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0012_auto_20190725_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stf',
            options={'ordering': ('-date_updated',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.County'),
        ),
        migrations.AlterField(
            model_name='local_link',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.City'),
        ),
        migrations.AlterField(
            model_name='local_link',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.County'),
        ),
    ]
