# Generated by Django 2.1.10 on 2019-07-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0013_auto_20190726_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='county',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
