# Generated by Django 2.1.10 on 2019-07-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0014_auto_20190730_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='county',
            new_name='counties',
        ),
    ]
