# Generated by Django 2.2.4 on 2019-08-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0016_auto_20190730_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='district',
            name='counties',
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ManyToManyField(related_name='cities', to='nodasf.City'),
        ),
        migrations.AddField(
            model_name='district',
            name='county',
            field=models.ManyToManyField(related_name='counties', to='nodasf.County'),
        ),
    ]
