# Generated by Django 2.2.4 on 2019-08-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0017_auto_20190806_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='stf_link',
            name='journalist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Journalist'),
        ),
    ]
