# Generated by Django 2.2.4 on 2019-08-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0019_auto_20190806_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.City'),
        ),
        migrations.AlterField(
            model_name='event',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.County'),
        ),
        migrations.AlterField(
            model_name='event',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.Genre'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.County'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.District'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.Level'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.Party'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='upcoming',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.Event'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.City'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.County'),
        ),
    ]
