# Generated by Django 2.2.4 on 2019-08-06 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0020_auto_20190806_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='agency',
            name='issue',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Issue'),
        ),
        migrations.AddField(
            model_name='organization',
            name='issue',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Issue'),
        ),
    ]
