# Generated by Django 2.2.4 on 2019-08-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0021_auto_20190806_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='candidate',
            field=models.BooleanField(default=False),
        ),
    ]
