# Generated by Django 2.2.4 on 2019-12-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0025_auto_20191203_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='first_name',
            field=models.CharField(default='first', max_length=200),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='last_name',
            field=models.CharField(default='last', max_length=200),
        ),
    ]
