# Generated by Django 2.2.4 on 2019-12-03 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0027_remove_journalist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='name',
        ),
        migrations.AddField(
            model_name='politician',
            name='first_name',
            field=models.CharField(default='first', max_length=100),
        ),
        migrations.AddField(
            model_name='politician',
            name='last_name',
            field=models.CharField(default='last', max_length=100),
        ),
        migrations.AlterField(
            model_name='politician',
            name='upcoming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.Event'),
        ),
    ]
