# Generated by Django 2.2.4 on 2019-12-05 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodasf', '0028_auto_20191203_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('homepage', models.CharField(default=' ', max_length=300)),
                ('description', models.TextField(default=' ')),
                ('imageQ', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/stock')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Category')),
                ('issue', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodasf.Issue')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodasf.Organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Bureaucrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='last', max_length=100)),
                ('first_name', models.CharField(default='first', max_length=100)),
                ('picture', models.ImageField(default=' ', upload_to='media/faces')),
                ('description', models.TextField()),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodasf.Organization')),
                ('program', models.ManyToManyField(blank=True, null=True, to='nodasf.Program')),
            ],
        ),
    ]
